name: commitlint
on:
  pull_request:
permissions:
  contents: read
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@a6949e51b30033872114623c1991d62e0673c75f # main
