name: publish
on:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write   # required for OIDC on the calling job
jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: unabandoned/.github/.github/workflows/reusable-publish.yml@a6949e51b30033872114623c1991d62e0673c75f # main
    with:
      install-for-publish: false
    secrets: inherit
