name: release-cut
on:
  schedule:
    - cron: '0 6 1 * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  cut:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-cut.yml@a6949e51b30033872114623c1991d62e0673c75f # main
    secrets: inherit
